version: '3'
services:
  mongodb:
    image: mongo:4.2.9
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_DATABASE=fruits
      - MONGO_INITDB_ROOT_USERNAME=mongodb
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    ports:
      - 27017:27017
    command: mongod